name: Deploy Backend to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./backend

      - name: Copy JAR to EC2
        run: |
          scp -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no \
            target/*.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app.jar

      - name: Restart backend on EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no \
            ubuntu@${{ secrets.EC2_HOST }} \
            'pkill -f app.jar || true; nohup java -jar /home/ubuntu/app.jar > app.log 2>&1 &'
